### ISSUE TITLE
nick not defined

### ISSUE THREAD

**Issue by tarlepp** [UniBot/unibot-karma#2]
Hi, I just noticed that ```!karma``` command without nick will crash this plugin.

```
ReferenceError: nick is not defined
    at ^!karma(?: (\S+))?$ (/home/wunder/projects/UniBot/node_modules/unibot-karma/index.js:106:26)
    at /home/wunder/projects/UniBot/lib/bot.js:27:5
    at forOwn (/home/wunder/projects/UniBot/node_modules/lodash/dist/lodash.js:1907:15)
    at Function.forEach (/home/wunder/projects/UniBot/node_modules/lodash/dist/lodash.js:3044:9)
    at /home/wunder/projects/UniBot/lib/bot.js:23:5
    at forOwn (/home/wunder/projects/UniBot/node_modules/lodash/dist/lodash.js:1907:15)
    at Function.forEach (/home/wunder/projects/UniBot/node_modules/lodash/dist/lodash.js:3044:9)
    at callPatterns (/home/wunder/projects/UniBot/lib/bot.js:22:4)
    at Client.join (/home/wunder/projects/UniBot/lib/bot.js:193:3)
    at Client.EventEmitter.emit (events.js:106:17)
```

**Comment by ProLoser** [comment]
If you don't specify a nick it should use yours

**Comment by ProLoser** [comment]
Line 105 should have an else nick = from
